#!/bin/bash

set -ex

# This is to solve as issue that ISCE does not support a VRT to read from a remote file identified with a URL.
# See https://github.com/isce-framework/isce2/pull/245 for more information.

isce_init=$(python -c "import isce; print('loc:' + isce.__file__)")
isce_init=${isce_init##*loc:}
echo "replacing ${isce_init%/*}/components/iscesys/ImageApi/DataAccessorPy.py with DataAccessorPy.py..."
cp DataAccessorPy.py ${isce_init%/*}/components/iscesys/ImageApi/DataAccessorPy.py
